plugins {
    id 'java'
    id 'maven-publish'
}

group 'de.arthurpicht'
version '0.0.5'
def artifact = 'ap-utils-struct'

repositories {
    maven { url "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases"}
    mavenCentral()
}

dependencies {
    implementation 'de.arthurpicht:ap-utils-core:1.19.0'
    implementation 'de.arthurpicht:ap-utils-io:0.0.23'

    implementation 'org.slf4j:slf4j-api:1.7.36'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.3'
    testRuntimeOnly 'ch.qos.logback:logback-classic:1.2.11'
}

java {
    withJavadocJar()
    withSourcesJar()
}

test {
    useJUnitPlatform()
}

base {
    archivesName = artifact
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = artifact
            from components.java
        }
    }
    repositories {
        maven {
            url = layout.buildDirectory.dir(project.gradle.gradleUserHomeDir.parent + "/gitrepos/ap/mvn-repo/releases")
        }
    }
}
